/**
 * Swagger SHome
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Memo { 
    platform?: string; // OS
    hostname?: string; // OS
    ip4? : string, //network
    speed? : string, //network
    dhcp? : string //network
    device?: string, // filesystem
    size?: string, // filesystem
    currentload?: string, // current Load
    currentsystem?: string, // current Load
    total?: string, // Memory
    free?: string, // Memory
    used?: string, // Memory
    main?: string, // temperature CPU
    localaddress?: string // net conex
    localport?: string // net conex


}
