/**
 * Swagger SHome
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Room { 
    camera?: number;
    temperatura?: number;
    umiditatea?: number;
    nivelGaz?: string;
    usa?: string;
    foc?: string;
    aer?: number;
    apa?: string;
    shipDate?: Date;
}
